#!/usr/bin/env bash

main() {
	local list=(
		"Lock"
		"Shutdown"
		"Reboot"
		"Logout"
		"Hibernate"
		"Suspend"
	)

	local options=(
		"--border=sharp"
		"--border-label= Power Menu "
		"--cycle"
		"--ghost=Search"
		"--height=~100%"
		"--highlight-line"
		"--info=inline-right"
		"--pointer="
		"--reverse"
	)

	local selected
	selected=$(printf "%s\n" "${list[@]}" | fzf "${options[@]}")

	case $selected in
		Lock) swaylock -f ;;
		Shutdown) systemctl poweroff ;;
		Reboot) systemctl reboot ;;
		Logout) swaymsg exit ;;
		Hibernate) systemctl hibernate ;;
		Suspend) systemctl suspend ;;
		*) return 1 ;;
	esac
}

main
