#!/usr/bin/env bash

DEF_VALUE=1
MIN=0
MAX=100

usage() {
	local script=${0##*/}

	cat <<EOF
USAGE: $script {input|output} {mute|raise|lower} [value]
EOF
}

pactl_cmd() {
	command pactl "$1" "$DEV_DEF" "${@:2}"
}

get_state() {
	local state
	state=$(pactl_cmd "get-$DEV_STATE" | awk '{print $2}')

	case $state in
		yes) printf "Muted" ;;
		no) printf "Unmuted" ;;
	esac
}

get_volume() {
	pactl_cmd "get-$DEV_VOLUME" | awk '{print $5}' | tr -d '%'
}

get_icon() {
	local state level icon
	state=$(get_state)
	level=$(get_volume)

	local new_level=${1:-$level}
	if [[ $state == Muted ]]; then
		icon="$DEV_ICON-muted"
	else
		if ((new_level < MAX * 33 / 100)); then
			icon="$DEV_ICON-low"
		elif ((new_level < MAX * 66 / 100)); then
			icon="$DEV_ICON-medium"
		else
			icon="$DEV_ICON-high"
		fi
	fi

	printf "%s" "$icon"
}

set_state() {
	pactl_cmd "set-$DEV_STATE" toggle

	local state icon
	state=$(get_state)
	icon=$(get_icon)

	notify-send "$DEV_NAME: $state" -i "$icon" \
		-h string:x-canonical-private-synchronous:volume
}

set_volume() {
	local level new_level icon
	level=$(get_volume)

	case $ACTION in
		raise)
			new_level=$((level + VALUE))
			if ((new_level > MAX)); then
				new_level=$MAX
			fi
			;;
		lower)
			new_level=$((level - VALUE))
			if ((new_level < MIN)); then
				new_level=$MIN
			fi
			;;
	esac

	pactl_cmd "set-$DEV_VOLUME" "$new_level%"
	icon=$(get_icon "$new_level")

	notify-send "$DEV_NAME: $new_level%" -h int:value:"$new_level" -i "$icon" \
		-h string:x-canonical-private-synchronous:volume
}

main() {
	DEVICE=$1
	ACTION=$2
	VALUE=${3:-$DEF_VALUE}

	if ((VALUE < 1)); then
		usage >&2
		return 1
	fi

	case $DEVICE in
		input)
			DEV_DEF="@DEFAULT_SOURCE@"
			DEV_STATE="source-mute"
			DEV_VOLUME="source-volume"
			DEV_ICON="mic-volume"
			DEV_NAME="Microphone"
			;;
		output)
			DEV_DEF="@DEFAULT_SINK@"
			DEV_STATE="sink-mute"
			DEV_VOLUME="sink-volume"
			DEV_ICON="audio-volume"
			DEV_NAME="Volume"
			;;
		*)
			usage >&2
			return 1
			;;
	esac

	case $ACTION in
		mute)
			set_state
			;;
		raise | lower)
			set_volume
			;;
		*)
			usage >&2
			return 1
			;;
	esac
}

main "$@"
